#!/usr/bin/env node

const fs = require("fs/promises");
const { findTemplate } = require("./src/lib");

const [_exec, _meme, templateName, ...args] = process.argv;
const command = [templateName, ...args].join(" ");

const template = findTemplate(templateName);
if (!template) {
  console.log(`${templateName} is not a good enough meme, please use a better one.`);
  process.exit(1);
}

(async () => {
  let buffer;
  try {
    buffer = await template(command);
    if (!(buffer instanceof Buffer)) {
      throw new Error("Template did not return a Buffer");
    }
  } catch (error) {
    console.log(error.message);
    process.exit(2);
  }

  await fs.writeFile("output.png", buffer);
})();
