name: Release

on:
  push:
    branches: ["release"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/foxfriends/memebot:latest
          build-args: |
            NPM_TOKEN=${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    environment: cameldridge.com
    needs:
      - release
    steps:
      - name: Trigger deploy
        run: |
          curl https://console.cameldridge.com/deploy2/memebot --header "X-Deploy-Secret: $DEPLOY_SECRET"
        env:
          DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
